package router

import (
	"net/http"
	"refactory-simpers-au/config"
	"refactory-simpers-au/internal/handler"
	"refactory-simpers-au/middleware"

	_ "refactory-simpers-au/docs" // docs is generated by Swag CLI, you have to import it

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin"
)

type Handler struct {
	SimpersHandler  handler.SimpersHandler
	PersonelHandler handler.PersonelHandler
	Middleware      middleware.Middleware
	Env             *config.EnvironmentVariable
}

func NewRouter(h Handler) *gin.Engine {
	r := gin.Default()

	r.Use(h.Middleware.CORSMiddleware())

	r.GET("", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"hello": "world",
		})
	})

	if h.Env.App.Mode == "dev" {
		SwaggerRouter(h.Env, r)
	}

	r.Use(otelgin.Middleware(h.Env.Tracer.ServiceName))
	r.Use(h.Middleware.TracerMiddleware())

	personel := r.Group("/personel")
	{
		personel.GET("/:nrp", h.SimpersHandler.GetPersonelByNRP)
		personel.GET("/:nrp/kartu_keluarga", h.SimpersHandler.GetFamilyCardByNRP)
		personel.GET("/:nrp/dikmil", h.SimpersHandler.GetDikMilByNRP)
		personel.GET("/:nrp/dikum", h.SimpersHandler.GetDikUmByNRP)
		personel.GET("/:nrp/jabatan", h.SimpersHandler.GetJabatanByNRP)
		personel.GET("/:nrp/tanhor", h.SimpersHandler.GetTanhorByNRP)
		personel.GET("/:nrp/pangkat", h.SimpersHandler.GetPangkatByNRP)
		personel.GET("/:nrp/lampiran_kk", h.SimpersHandler.GetLampiranKKByNRP)
		personel.GET("/:nrp/npwp", h.SimpersHandler.GetNPWPByNRP)
		personel.GET("/:nrp/asabri", h.SimpersHandler.GetAsabriByNRP)
		personel.GET("/:nrp/paspor", h.SimpersHandler.GetPasporByNRP)
	}
	r.POST("/lampiran", h.SimpersHandler.CreateLampiranDokumen)
	r.POST("/:tipe-dokumen/:id-dokumen/lampiran", h.SimpersHandler.CreateLampiran)

	return r
}

func SwaggerRouter(env *config.EnvironmentVariable, router *gin.Engine) {
	router.GET(env.Swagger.BasePath+"/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

}
